# Generated by Django 4.2.7 on 2024-03-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('sizr_sq_feet', models.CharField(max_length=50)),
            ],
        ),
    ]
